default_platform :ios

platform :ios do
  skip_docs

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: 'UI/Layer-XDK-UI.xcworkspace',
      scheme: "Layer-XDK-UI-UnitTests"
    )
  end
end
