default_platform :ios

platform :ios do
  skip_docs

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan( 
      scheme: "Atlas"
    )
    scan(
      scheme: "Programmatic"
    )
    scan(
      scheme: "Storyboard"
    )
  end
end
